language: php
sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

before_script:
  - composer self-update
  - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
